name: Life-USTC
options:
  bundleIdPrefix: com.linzihan
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "2.2.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    DEVELOPMENT_TEAM: VUW8FV5HN5
    CODE_SIGN_STYLE: Manual

targets:
  Life-USTC:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: "Assets/"
      - path: "General/"
      - path: "Models/"
      - path: "Schools/"
      - path: "Views/"
      - path: "AppDelegate.swift"
      - path: "LaunchScreen.storyboard"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.tiankaima.Life-USTC
        PRODUCT_NAME: Life@USTC
        PROVISIONING_PROFILE_SPECIFIER: "match Development dev.tiankaima.Life-USTC"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSCalendarsUsageDescription: "向日历中添加课表/考试信息"
        INFOPLIST_KEY_NSRemindersUsageDescription: "向日历中添加课表/考试信息"
        OTHER_LDFLAGS: "-ObjC"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    entitlements:
      path: Life-USTC.entitlements
      properties:
        aps-environment: development
        com.apple.developer.associated-domains:
          - webcredentials:passport.ustc.edu.cn
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.dev.tiankaima.Life-USTC
        com.apple.security.network.client: true
        com.apple.security.personal-information.calendars: true
    dependencies:
      - sdk: Foundation.framework
      - sdk: UIKit.framework
      - sdk: CoreGraphics.framework
      - sdk: CoreLocation.framework
      - sdk: CoreTelephony.framework
      - sdk: Security.framework
      - sdk: SystemConfiguration.framework
      - package: FeedKit
      - package: Introspect
      - package: SwiftyJSON
      - package: SwiftSoup
      - package: Reeeed
      - package: LoremSwiftum
      - package: KeychainAccess
      - package: ScreenshotPreventingSwiftUI
      - target: Widget iOS
    info:
      path: Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        ITSAppUsesNonExemptEncryption: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
          NSAllowsArbitraryLoadsForMedia: true
          NSAllowsArbitraryLoadsInWebContent: true
          NSExceptionDomains:
            ustc.edu.cn:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
        NSCalendarsUsageDescription: "向日历中添加课表/考试信息"
        NSCalendarsFullAccessUsageDescription: "向日历中添加课表/考试信息"
        NSRemindersFullAccessUsageDescription: "向日历中添加课表/考试信息"
        NSPrivacyAccessedAPITypes:
          - NSPrivacyAccessedAPIType: NSPrivacyAccessedAPICategoryUserDefaults
            NSPrivacyAccessedAPITypeReasons: ["1C8F.1"]
        NSUserActivityTypes:
          - ConfigurationIntent
        UIBackgroundModes:
          - fetch
        UILaunchScreen:
          UIImageName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSupportsIndirectInputEvents: true
        UISupportedInterfaceOrientations:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationPortraitUpsideDown,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
          ]
        BGTaskSchedulerPermittedIdentifiers:
          - dev.tiankaima.Life-USTC.background_refresh

  Widget iOS:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: "Widget/"
      - path: "Assets/"
      - path: "General/"
      - path: "Models/"
      - path: "Schools/"
      - path: "Views/General/"
        excludes:
          - "PushNotification/**"
      - path: "Views/Extensions/"
        excludes:
          - "ContentViewTab.swift"
    entitlements:
      path: Widget/Widget.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.dev.tiankaima.Life-USTC
        com.apple.security.network.client: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.tiankaima.Life-USTC.Widget
        PRODUCT_NAME: "Widget iOS"
        PROVISIONING_PROFILE_SPECIFIER: "match Development dev.tiankaima.Life-USTC.Widget"
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        SKIP_INSTALL: YES
    dependencies:
      - package: FeedKit
      - package: Introspect
      - package: SwiftyJSON
      - package: SwiftSoup
      - package: Reeeed
      - package: LoremSwiftum
      - package: KeychainAccess
    info:
      path: Widget/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleDisplayName: "Life@USTC"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

packages:
  FeedKit:
    url: https://github.com/nmdias/FeedKit
    majorVersion: 9.1.2
  Introspect:
    url: https://github.com/siteline/SwiftUI-Introspect.git
    majorVersion: 0.1.4
  SwiftyJSON:
    url: https://github.com/SwiftyJSON/SwiftyJSON
    majorVersion: 5.0.1
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup
    majorVersion: 2.5.3
  Reeeed:
    url: https://github.com/tiankaima/reeeed
    branch: main
  LoremSwiftum:
    url: https://github.com/lukaskubanek/LoremSwiftum
    branch: master
  ScreenshotPreventingSwiftUI:
    url: https://github.com/yoxisem544/ScreenshotPreventing-iOS
    from: 1.4.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    branch: master

schemes:
  Life-USTC:
    build:
      targets:
        Life-USTC: all
      preActions:
        - script: "# Type a script or drag a script file from your workspace to insert its path."
          name: Run Script
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  "Widget (Exam)":
    build:
      targets:
        "Widget iOS": [run, build]
        Life-USTC: [build]
    run:
      config: Debug
      commandLineArguments: {}
      environmentVariables:
        _XCWidgetKind: ExamWidget
        _XCWidgetDefaultView: timeline
        _XCWidgetFamily: systemLarge

  "Widget (Curriculum)":
    build:
      targets:
        "Widget iOS": [run, build]
        Life-USTC: [build]
    run:
      config: Debug
      commandLineArguments: {}
      environmentVariables:
        _XCWidgetKind: CurriculumPreviewWidget
        _XCWidgetDefaultView: timeline
        _XCWidgetFamily: systemMedium

  "Widget (CurriculumWeekWidget)":
    build:
      targets:
        "Widget iOS": [run, build]
        Life-USTC: [build]
    run:
      config: Debug
      commandLineArguments: {}
      environmentVariables:
        _XCWidgetKind: CurriculumWeekWidget
        _XCWidgetDefaultView: timeline
        _XCWidgetFamily: systemExtraLarge
