//
//  USTC+QCKDExamples.swift
//  Life@USTC
//
//  Created by Tiankai Ma on 2023/7/25.
//

import SwiftyJSON

extension UstcQCKDEvent {
    static var example: UstcQCKDEvent = {
        var json = JSON()
        json["children"] = JSON(parseJSON: """
        [{
        "id": "60ab4628592df0f648aaf890dd242e0b",
        "itemName": "体育提升营子活动5",
        "module": "t",
        "form": "1",
        "activityLevel": "college",
        "itemLable": "1296303933553553410,1296303797716824066,1296304057109360642",
        "totalServiceHour": null,
        "serviceHour": "3.0",
        "validHour": 3.00,
        "libId": "",
        "linkMan": "胡玥",
        "tel": "0551-63602795",
        "sponsor": "000",
        "ewSponsor": null,
        "organizer": "000",
        "type": 0,
        "pic": "group1/M00/16/79/wKgUEWS6eFyAVTgNAAHqxSij5xU314.jpg",
        "baseContent": "活动旨在培养学生体育运动兴趣和特长，促使学生掌握体育运动技能，促进学生养成终身锻炼的习惯。",
        "baseContentCountNum": null,
        "examineStatus": 10,
        "examineStatusName": null,
        "itemStatus": 26,
        "applyStatus": 26,
        "needApply": "1",
        "st": "2023-07-21 20:21:00",
        "et": "2023-07-26 23:21:00",
        "rangeDeptIds": null,
        "nj": null,
        "xq": null,
        "peopleNum": 100,
        "teamNum": null,
        "teamSize": null,
        "delFlag": 0,
        "createBy": "10542",
        "createTime": "2023-07-21 20:23:55",
        "updateBy": "PB21000095",
        "updateTime": "2023-07-25 10:38:00",
        "applyRange": "3",
        "applyWay": "0",
        "review": "0",
        "stick": "0",
        "showWininfo": "0",
        "putaway": "0",
        "delAudit": 1,
        "planningAtta": null,
        "businessDeptId": "000",
        "needPlaceApply": "0",
        "applySt": "2023-07-21 20:21:00",
        "applyEt": "2023-07-26 20:21:00",
        "actionStatus": null,
        "processInstanceId": "5757756",
        "processType": 0,
        "qrSigninClosed": "0",
        "enshrine": null,
        "booleanRegistration": 1,
        "qrSignoffClosed": "0",
        "enshrineNum": null,
        "modules": null,
        "lastApprovalMan": "10542",
        "applyNum": 9,
        "applyTeamNum": null,
        "itemCategory": "0",
        "attaType": "doc,docx,ppt,pptx,png,pdf,jpg,zip",
        "pid": "620a4aaefa045d7d114b441cabfed94c",
        "itemLimitNum": null,
        "holdingPeriod": null,
        "attaEndTime": null,
        "uuidKey": "39a95772bb514ba2bcd44b14a4eb602f",
        "registrationStatus": null,
        "itemPlaceDTO": null,
        "evaluated": null,
        "duration": 123.0,
        "businessDeptName": "少年班学院（少年班、教改试点班）",
        "version": null,
        "workStatus": null,
        "budgetList": null,
        "backOaBudget": 0,
        "hours": null,
        "conceive": "请提交参加本次体育提升营的心得体会（200字以上）及照片3张",
        "conceiveCountNum": null,
        "outlayMoney": 0.00,
        "outlayDetail": null,
        "placeInfo": null,
        "identity": null,
        "labelTo": null,
        "departTo": null,
        "cancelSign": 0,
        "evaluation": 0,
        "canGivenHours": false,
        "canSubmitWork": true,
        "proposalId": null,
        "isKnot": 0,
        "budgetProjectId": null,
        "createst": null,
        "createet": null,
        "partakeNum": 0,
        "sumHours": 0.00,
        "sumPersons": 4,
        "needSignInfo": "0",
        "hosting": "1",
        "signInfo": 0,
        "auditTime": "2023-07-21 20:26:10",
        "publicEndTime": null,
        "qdClassId": null,
        "qdCourseStatus": null,
        "qdClassIndex": null,
        "isShowShare": 0,
        "regOptions": null,
        "regRemarks": null,
        "regPicUrls": null,
        "module_dictText": "体",
        "form_dictText": "提交作品",
        "endTime": null,
        "itemStatus_dictText": "报名中",
        "signInType": null,
        "signOutType": null
        }]
        """)

        json["self"] = JSON(parseJSON: """
        {
        "id": "620a4aaefa045d7d114b441cabfed94c",
        "itemName": "少年班学院春季学期体育提升营",
        "module": "t",
        "form": "1",
        "activityLevel": "college",
        "itemLable": "1296303933553553410,1296303797716824066,1296304057109360642",
        "totalServiceHour": null,
        "serviceHour": null,
        "validHour": null,
        "libId": "",
        "linkMan": "胡玥",
        "tel": "0551-63602795",
        "sponsor": "000",
        "ewSponsor": null,
        "organizer": "000",
        "type": 0,
        "pic": "group1/M00/16/79/wKgUEWS6ciSAenARAAHp9E7wcjM783.jpg",
        "baseContent": "活动旨在培养学生体育运动兴趣和特长，促使学生掌握体育运动技能，促进学生养成终身锻炼的习惯。",
        "baseContentCountNum": null,
        "examineStatus": 10,
        "examineStatusName": null,
        "itemStatus": 26,
        "applyStatus": 26,
        "needApply": "1",
        "st": "2023-07-21 19:55:00",
        "et": "2023-07-30 19:55:00",
        "rangeDeptIds": null,
        "nj": null,
        "xq": null,
        "peopleNum": null,
        "teamNum": null,
        "teamSize": null,
        "delFlag": 0,
        "createBy": "10542",
        "createTime": "2023-07-21 20:00:30",
        "updateBy": "10542",
        "updateTime": "2023-07-21 20:00:30",
        "applyRange": "3",
        "applyWay": "0",
        "review": "0",
        "stick": "0",
        "showWininfo": "0",
        "putaway": "0",
        "delAudit": 1,
        "planningAtta": null,
        "businessDeptId": "000",
        "needPlaceApply": "0",
        "applySt": null,
        "applyEt": null,
        "actionStatus": null,
        "processInstanceId": "5757716",
        "processType": 0,
        "qrSigninClosed": "0",
        "enshrine": null,
        "booleanRegistration": 0,
        "qrSignoffClosed": "0",
        "enshrineNum": null,
        "modules": null,
        "lastApprovalMan": "10542",
        "applyNum": 0,
        "applyTeamNum": null,
        "itemCategory": "1",
        "attaType": null,
        "pid": "-1",
        "itemLimitNum": 10,
        "holdingPeriod": null,
        "attaEndTime": null,
        "uuidKey": "db8d7b1f9ec14fd5b01479fa61eb1a63",
        "registrationStatus": null,
        "itemPlaceDTO": null,
        "evaluated": null,
        "duration": 216.0,
        "businessDeptName": null,
        "version": null,
        "workStatus": null,
        "budgetList": [
            {
                "id": 38701,
                "itemId": "620a4aaefa045d7d114b441cabfed94c",
                "budgetType": null,
                "budgetType_text": null,
                "name": "",
                "perPrize": null,
                "num": null,
                "sumPrize": 0,
                "createBy": "10542",
                "createTime": "2023-07-21 20:00:30",
                "updateBy": null,
                "updateTime": "2023-07-21 20:00:30",
                "oaBudgetId": null,
                "oaProjectId": null,
                "xn": "2022-2023",
                "xq": "2",
                "deptId": "000",
                "locked": 0
            }
        ],
        "backOaBudget": 0,
        "hours": null,
        "conceive": "授课内容主要面向该项目零基础或水平较低的学生。各项目均采用小班教学。",
        "conceiveCountNum": null,
        "outlayMoney": 0.00,
        "outlayDetail": null,
        "placeInfo": null,
        "identity": null,
        "labelTo": null,
        "departTo": null,
        "cancelSign": 0,
        "evaluation": 0,
        "canGivenHours": false,
        "canSubmitWork": true,
        "proposalId": null,
        "isKnot": 0,
        "budgetProjectId": null,
        "createst": null,
        "createet": null,
        "partakeNum": 0,
        "sumHours": 0.00,
        "sumPersons": 0,
        "needSignInfo": "0",
        "hosting": "1",
        "signInfo": 0,
        "auditTime": "2023-07-21 20:01:26",
        "publicEndTime": null,
        "qdClassId": null,
        "qdCourseStatus": null,
        "qdClassIndex": null,
        "isShowShare": 0,
        "regOptions": null,
        "regRemarks": null,
        "regPicUrls": null,
        "libName": null,
        "moduleName": "体",
        "formName": "提交作品",
        "itemLevelName": "院级",
        "lableNames": "思想提升,体育健身,技能培训",
        "sponsorNames": "少年班学院（少年班、教改试点班）",
        "organizerNames": "少年班学院（少年班、教改试点班）",
        "bussinessDeptName": "少年班学院（少年班、教改试点班）",
        "itemTypeName": "普通项目",
        "itemCategoryName": "系列项目",
        "processTypeName": "机构申请",
        "rangeDeptName": null,
        "njName": null,
        "signInType": null,
        "signOutType": null
        }
        """)

        json["rating"] = JSON(parseJSON: """
        {
        "avgNum": "5.00",
        "evaluationNum": 10,
        "registrationNum": 65
        }
        """)
        return UstcQCKDEvent(json: json)
    }()
}
