platform :ios do
  # ! Local methods:
  desc "Generate new certificates"
  lane :generate_new_certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ["dev.tiankaima.Life-USTC", "dev.tiankaima.Life-USTC.Widget"],
      force_for_new_devices: true,
      readonly: false,
    )

    sync_code_signing(
      type: "appstore",
      app_identifier: ["dev.tiankaima.Life-USTC", "dev.tiankaima.Life-USTC.Widget"],
      readonly: false,
    )
  end

  #! Local testings:
  desc "Build"
  lane :build do
    certificates
    build_app(
      scheme: "Life@USTC",
      export_options: {
        method: "app-store",
        uploadSymbols: true,
        provisioningProfiles: {
          "dev.tiankaima.Life-USTC": "match AppStore dev.tiankaima.Life-USTC",
          "dev.tiankaima.Life-USTC.Widget": "match AppStore dev.tiankaima.Life-USTC.Widget",
        },
      },
    )
  end

  # ! CI methods:
  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ["dev.tiankaima.Life-USTC", "dev.tiankaima.Life-USTC.Widget"],
      force_for_new_devices: true,
      readonly: true,
    )

    sync_code_signing(
      type: "appstore",
      app_identifier: ["dev.tiankaima.Life-USTC", "dev.tiankaima.Life-USTC.Widget"],
      readonly: true,
    )
  end

  desc "Load ASC API Keys"
  lane :load_asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY"],
      is_key_content_base64: true,
      in_house: false,
    )
  end

  desc "Bump build number based TestFlight"
  lane :fetch_and_increment_build_number do
    app_identifier = "dev.tiankaima.Life-USTC"
    api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]

    current_version = get_version_number(
      target: "Life@USTC",
    )

    latest_build_number = latest_testflight_build_number(
      api_key: api_key,
      version: current_version,
      app_identifier: app_identifier,
    )

    increment_build_number(
      build_number: (latest_build_number + 1),
    )
  end

  desc "Deploy to Testflight"
  lane :deploy do
    setup_ci
    load_asc_api_key
    certificates

    fetch_and_increment_build_number
    build_app(scheme: "Life@USTC")

    # upload_to_app_store(
    #   force: true,
    #   run_precheck_before_submit: false,
    #   submit_for_review: false,
    # )

    upload_to_testflight(
      distribute_external: true,
      changelog: ENV["COMMIT_MESSAGE"],
      distribute_only: false,
      groups: [
        "Internal",
        "External",
      ],
      skip_submission: true,
      notify_external_testers: true,
      skip_waiting_for_build_processing: true,
    )
  end

  desc "Update version number (if env['GITHUB-TAG'] contains tag in format v1.2.3)"
  lane :update_version_number do
    tag = ENV["GITHUB_TAG"]
    if tag.start_with?("v")
      increment_version_number(
        version_number: tag[1..],
      )
    end
  end

  desc "Deploy to App Store"
  lane :deploy_to_app_store do
    setup_ci
    load_asc_api_key
    certificates

    fetch_and_increment_build_number
    build_app(scheme: "Life@USTC")

    upload_to_app_store(
      force: true,
      run_precheck_before_submit: false,
      submit_for_review: false,
    )
  end
end
