platform :ios do
  desc "Build"
  lane :build do
    setup_ci if is_ci
    xcode_select("/Applications/Xcode_15.0.app") if is_ci
    match(type: "development", readonly: is_ci)
    match(type: "appstore", readonly: is_ci)
    gym(
      scheme: "Life@USTC",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.linzihan.XZKDiOS": "match AppStore com.linzihan.XZKDiOS",
          "com.linzihan.XZKDiOS.Widget": "match AppStore com.linzihan.XZKDiOS.Widget",
        },
      },
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    setup_ci if is_ci
    xcode_select("/Applications/Xcode_15.0.app") if is_ci
    match(type: "development", readonly: is_ci)
    match(type: "appstore", readonly: is_ci)
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY"],
      is_key_content_base64: true,
      in_house: false,
    )
    increment_build_number({
      build_number: latest_testflight_build_number(
        version: get_version_number(
          target: "Life@USTC",
        ),
        app_identifier: "dev.tiankaima.Life-USTC",
      ) + 1,
    })
    gym(
      scheme: "Life@USTC",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.linzihan.XZKDiOS": "match AppStore com.linzihan.XZKDiOS",
          "com.linzihan.XZKDiOS.Widget": "match AppStore com.linzihan.XZKDiOS.Widget",
        },
      },
    )
    pilot(skip_waiting_for_build_processing: true)
  end
end
