# ios_version("26.0.1")

devices([
  # iPhone sizes
  "iPhone 14 Pro Max",
  # "iPhone 14 Plus",
  # "iPhone 14 Pro",
  # "iPhone 14",

  # iPad sizes
  # "iPad Pro (12.9-inch) (3rd generation)",
  # "iPad Air (3rd generation)",
  # "iPad mini (5th generation)",
])

languages([
    "en-US",
    "zh-Hans"
])

scheme("Life-USTC-UITests")

output_directory("./screenshots")

clear_previous_screenshots(true)

override_status_bar(true)
