name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: macos-26
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: actions/checkout@v5

      - name: Setup .xcodeproj
        run: |
          brew install xcodegen
          xcodegen --spec project.yml

      - name: Build IPA
        run: fastlane ios build_ipa
        env:
          TZ: Asia/Shanghai
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
