name: iOS binary build & upload

on:
    push:
        branches:
            - "*"
    workflow_dispatch:

jobs:
    deploy:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build & upload iOS binary
              run: fastlane build_upload_testflight
              env:
                  ASC_KEY_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
                  ASC_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
                  ASC_KEY: ${{ secrets.AUTH_KEY }}
                  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

            - name: Upload app-store ipa and dsyms to artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: app-store ipa & dsyms
                  path: |
                      ${{ github.workspace }}/example-iOS.ipa
                      ${{ github.workspace }}/*.app.dSYM.zip
